name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlibig-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev;
                  export JAVA_HOME=/usr/lib/jvm/jdk-17;
                  export PATH=$JAVA_HOME/bin:$PATH;
                  pip3 install --user --upgrade Cython==0.29.33 virtualenv;
                  buildozer android debug
          repository_root: main
          workdir: .
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          ref: main # Branch name

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Push binary to data branch
        if: github.event_name == 'push'
        run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin
